CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(32) NOT NULL,
    balance_side VARCHAR(16) NOT NULL,
    parent_code VARCHAR(32),
    level_no INT NOT NULL DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    partner_type VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE column_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_type VARCHAR(40) NOT NULL,
    name VARCHAR(100) NOT NULL,
    mapping_json CLOB NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_type VARCHAR(40) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    period VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    success_rows INT NOT NULL DEFAULT 0,
    error_rows INT NOT NULL DEFAULT 0,
    message VARCHAR(2000),
    created_by VARCHAR(64),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_import_batches_period ON import_batches (period);
CREATE INDEX idx_import_batches_hash ON import_batches (file_hash, import_type, period);

CREATE TABLE import_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    row_number INT NOT NULL,
    raw_json CLOB,
    error_message VARCHAR(2000) NOT NULL,
    CONSTRAINT fk_ex_batch FOREIGN KEY (batch_id) REFERENCES import_batches (id) ON DELETE CASCADE
);

CREATE INDEX idx_import_exceptions_batch ON import_exceptions (batch_id);

CREATE TABLE account_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    period VARCHAR(16) NOT NULL,
    account_code VARCHAR(32) NOT NULL,
    account_name VARCHAR(200),
    opening_debit DECIMAL(18,2) NOT NULL DEFAULT 0,
    opening_credit DECIMAL(18,2) NOT NULL DEFAULT 0,
    period_debit DECIMAL(18,2) NOT NULL DEFAULT 0,
    period_credit DECIMAL(18,2) NOT NULL DEFAULT 0,
    closing_debit DECIMAL(18,2) NOT NULL DEFAULT 0,
    closing_credit DECIMAL(18,2) NOT NULL DEFAULT 0,
    partner_code VARCHAR(32)
);

CREATE INDEX idx_balances_period ON account_balances (period);
CREATE INDEX idx_balances_batch ON account_balances (batch_id);

CREATE TABLE bank_statement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    period VARCHAR(16) NOT NULL,
    txn_date DATE NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    counterparty VARCHAR(200),
    summary VARCHAR(500),
    bank_account VARCHAR(64),
    ref_no VARCHAR(64),
    balance_after DECIMAL(18,2),
    matched BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_bank_period ON bank_statement_lines (period);

CREATE TABLE cash_journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    period VARCHAR(16) NOT NULL,
    txn_date DATE NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    account_code VARCHAR(32),
    counterparty VARCHAR(200),
    summary VARCHAR(500),
    voucher_no VARCHAR(64),
    matched BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_journal_period ON cash_journal_lines (period);

CREATE TABLE recon_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period VARCHAR(16) NOT NULL,
    statement_id BIGINT NOT NULL,
    journal_id BIGINT NOT NULL,
    match_type VARCHAR(16) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    date_diff_days INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_recon_period ON recon_matches (period);

CREATE TABLE report_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(40) NOT NULL,
    line_code VARCHAR(32) NOT NULL,
    line_name VARCHAR(200) NOT NULL,
    section VARCHAR(64),
    line_kind VARCHAR(16) NOT NULL,
    formula_expr VARCHAR(500),
    sort_order INT NOT NULL,
    indent INT NOT NULL DEFAULT 0,
    UNIQUE (report_type, line_code)
);

CREATE TABLE report_formulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(40) NOT NULL,
    line_code VARCHAR(32) NOT NULL,
    account_code VARCHAR(32) NOT NULL,
    multiplier DECIMAL(8,2) NOT NULL DEFAULT 1
);

CREATE INDEX idx_formula_line ON report_formulas (report_type, line_code);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(64),
    entity_id VARCHAR(64),
    detail VARCHAR(2000),
    username VARCHAR(64),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_created ON audit_logs (created_at);

CREATE TABLE app_settings (
    setting_key VARCHAR(64) PRIMARY KEY,
    setting_value VARCHAR(500) NOT NULL
);
